name: workflow1
on: push
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies        
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

      - name: Build code
        run: npm run build 
